name: Trigger auto deployment for glider-polar-analysis-tool

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/glider-polar-analysis-tool-AutoDeployTrigger-5258a439-60d7-49f7-b84a-84a2d486c3db.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.GLIDERPOLARANALYSISTOOL_REGISTRY_USERNAME }}
          password: ${{ secrets.GLIDERPOLARANALYSISTOOL_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tfraudet/glider-polar-analysis-tool:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GLIDERPOLARANALYSISTOOL_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n glider-polar-analysis-tool -g acph-pre-prod --server docker.io --username  ${{ secrets.GLIDERPOLARANALYSISTOOL_REGISTRY_USERNAME }} --password ${{ secrets.GLIDERPOLARANALYSISTOOL_REGISTRY_PASSWORD }}
            az containerapp update -n glider-polar-analysis-tool -g acph-pre-prod --image tfraudet/glider-polar-analysis-tool:${{ github.sha }}
