name: Build docker image & deploy it to Azure Container App

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  #push:
    #branches: 
      #[ main ]
    #paths:
    #- '**'
    #- '.github/workflows/glider-polar-analysis-tool-AutoDeployTrigger-5258a439-60d7-49f7-b84a-84a2d486c3db.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to container registry Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/glider-polar-analysis-tool:${{ github.sha }}
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/gliderpolaranalysis:latest
          file: ./Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n glider-polar-analysis-tool -g acph-pre-prod --server docker.io --username  ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            az containerapp update -n glider-polar-analysis-tool -g acph-pre-prod --image ${{ secrets.DOCKERHUB_USERNAME }}/glider-polar-analysis-tool:${{ github.sha }}
